// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6jdiTgRhkYQJ2zXFv6Yaw9
// Component: AEg-Kqw64T
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NewstakingPopup from "../../NewstakingPopup"; // plasmic-import: 6NrxLI77CT/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_joss_staking.module.css"; // plasmic-import: 6jdiTgRhkYQJ2zXFv6Yaw9/projectcss
import sty from "./PlasmicOverlay.module.css"; // plasmic-import: AEg-Kqw64T/css

export type PlasmicOverlay__VariantMembers = {};

export type PlasmicOverlay__VariantsArgs = {};
type VariantPropType = keyof PlasmicOverlay__VariantsArgs;
export const PlasmicOverlay__VariantProps = new Array<VariantPropType>();

export type PlasmicOverlay__ArgsType = {};
type ArgPropType = keyof PlasmicOverlay__ArgsType;
export const PlasmicOverlay__ArgProps = new Array<ArgPropType>();

export type PlasmicOverlay__OverridesType = {
  root?: p.Flex<"div">;
  newstakingPopup?: p.Flex<typeof NewstakingPopup>;
};

export interface DefaultOverlayProps {
  className?: string;
}

function PlasmicOverlay__RenderFunc(props: {
  variants: PlasmicOverlay__VariantsArgs;
  args: PlasmicOverlay__ArgsType;
  overrides: PlasmicOverlay__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      id={"newStakeOverlay" as const}
    >
      <NewstakingPopup
        data-plasmic-name={"newstakingPopup"}
        data-plasmic-override={overrides.newstakingPopup}
        className={classNames("__wab_instance", sty.newstakingPopup)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "newstakingPopup"],
  newstakingPopup: ["newstakingPopup"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  newstakingPopup: typeof NewstakingPopup;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOverlay__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOverlay__VariantsArgs;
    args?: PlasmicOverlay__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOverlay__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicOverlay__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicOverlay__ArgProps,
          internalVariantPropNames: PlasmicOverlay__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicOverlay__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOverlay";
  } else {
    func.displayName = `PlasmicOverlay.${nodeName}`;
  }
  return func;
}

export const PlasmicOverlay = Object.assign(
  // Top-level PlasmicOverlay renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    newstakingPopup: makeNodeComponent("newstakingPopup"),

    // Metadata about props expected for PlasmicOverlay
    internalVariantProps: PlasmicOverlay__VariantProps,
    internalArgProps: PlasmicOverlay__ArgProps
  }
);

export default PlasmicOverlay;
/* prettier-ignore-end */
