// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6jdiTgRhkYQJ2zXFv6Yaw9
// Component: liD_GqO12rk
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: KhBkDGlzke/component
import Menubar from "../../Menubar"; // plasmic-import: bkX_qKyhqs/component
import MnItem from "../../MnItem"; // plasmic-import: OUU_m6iRfO/component
import Footer from "../../Footer"; // plasmic-import: oeSuO0WaA0/component

import { useScreenVariants as useScreenVariantsyddWx7I3Gw2DK } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: YddWx7I3Gw2dK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_joss_staking.module.css"; // plasmic-import: 6jdiTgRhkYQJ2zXFv6Yaw9/projectcss
import sty from "./PlasmicActivity.module.css"; // plasmic-import: liD_GqO12rk/css

export type PlasmicActivity__VariantMembers = {};

export type PlasmicActivity__VariantsArgs = {};
type VariantPropType = keyof PlasmicActivity__VariantsArgs;
export const PlasmicActivity__VariantProps = new Array<VariantPropType>();

export type PlasmicActivity__ArgsType = {};
type ArgPropType = keyof PlasmicActivity__ArgsType;
export const PlasmicActivity__ArgProps = new Array<ArgPropType>();

export type PlasmicActivity__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  contentWrapper?: p.Flex<"section">;
  content?: p.Flex<"div">;
  head?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  menubar?: p.Flex<typeof Menubar>;
  portoflioWapper?: p.Flex<"div">;
  h3?: p.Flex<"h3">;
  tabel?: p.Flex<"div">;
  tableHeader?: p.Flex<"div">;
  tableContent?: p.Flex<"div">;
  tableContent2?: p.Flex<"div">;
  tableContent3?: p.Flex<"div">;
  tableContent4?: p.Flex<"div">;
  tableContent5?: p.Flex<"div">;
  tableContent6?: p.Flex<"div">;
  tableContent7?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultActivityProps {}

function PlasmicActivity__RenderFunc(props: {
  variants: PlasmicActivity__VariantsArgs;
  args: PlasmicActivity__ArgsType;
  overrides: PlasmicActivity__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsyddWx7I3Gw2DK()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <p.Stack
            as={"section"}
            data-plasmic-name={"contentWrapper"}
            data-plasmic-override={overrides.contentWrapper}
            hasGap={true}
            className={classNames(projectcss.all, sty.contentWrapper)}
          >
            <div
              data-plasmic-name={"content"}
              data-plasmic-override={overrides.content}
              className={classNames(projectcss.all, sty.content)}
            >
              <div
                data-plasmic-name={"head"}
                data-plasmic-override={overrides.head}
                className={classNames(projectcss.all, sty.head)}
              >
                <div className={classNames(projectcss.all, sty.column__s5Y3Z)}>
                  {true ? (
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Activity"}
                    </h1>
                  ) : null}
                </div>

                <div className={classNames(projectcss.all, sty.column___16Vvb)}>
                  <Menubar
                    data-plasmic-name={"menubar"}
                    data-plasmic-override={overrides.menubar}
                    activity={
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__r3OC
                        )}
                        component={Link}
                        href={`/activity`}
                        platform={"nextjs"}
                      >
                        <MnItem
                          className={classNames(
                            "__wab_instance",
                            sty.mnItem__djPe0
                          )}
                          isActive={true}
                        >
                          {"Activity"}
                        </MnItem>
                      </p.PlasmicLink>
                    }
                    className={classNames("__wab_instance", sty.menubar)}
                    dashboard={
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__sV0MG
                        )}
                        component={Link}
                        href={`/`}
                        platform={"nextjs"}
                      >
                        <MnItem
                          className={classNames(
                            "__wab_instance",
                            sty.mnItem__do1Nx
                          )}
                        >
                          {"Dashboard"}
                        </MnItem>
                      </p.PlasmicLink>
                    }
                  />
                </div>
              </div>

              {true ? (
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"portoflioWapper"}
                  data-plasmic-override={overrides.portoflioWapper}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.portoflioWapper)}
                >
                  {true ? (
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"My Activity"}
                    </h3>
                  ) : null}

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tabel"}
                    data-plasmic-override={overrides.tabel}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tabel)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <div
                        data-plasmic-name={"tableHeader"}
                        data-plasmic-override={overrides.tableHeader}
                        className={classNames(projectcss.all, sty.tableHeader)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___7Gc5H
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ziS0Q
                            )}
                          >
                            {"Time"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__sq0MZ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0FLig
                            )}
                          >
                            {"Transaction Type"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__gaTnn
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__luh9L
                            )}
                          >
                            {"Portfolio Name"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___9D8ZQ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xdhIy
                            )}
                          >
                            {"Product Name"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__hZxMx
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4PJro
                            )}
                          >
                            {"Amount"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___3LCo5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__whoIt
                            )}
                          >
                            {"Status"}
                          </div>
                        </div>
                      </div>
                    ) : null}

                    <div
                      data-plasmic-name={"tableContent"}
                      data-plasmic-override={overrides.tableContent}
                      className={classNames(projectcss.all, sty.tableContent)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nO32S
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__muObA
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___5Qlr6
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___52Fvz
                          )}
                        >
                          {"New Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9Hg1N
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vccSs
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rvDCh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dugdY
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__x2WgZ
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ijUes
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ai9DZ
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f0N1O
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent2"}
                      data-plasmic-override={overrides.tableContent2}
                      className={classNames(projectcss.all, sty.tableContent2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uy76V
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hJBrI
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__aEygh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8CUag
                          )}
                        >
                          {"Claim"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__oyWQg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wkA39
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3WKgo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oWpt5
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__jTx5K
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kVnNh
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cGhUb
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9WvZo
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent3"}
                      data-plasmic-override={overrides.tableContent3}
                      className={classNames(projectcss.all, sty.tableContent3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__qlIrg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rmipN
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uusGw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8JlgB
                          )}
                        >
                          {"Un Stake"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__boEzz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rukVh
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4GCzg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pWJoi
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9HJv5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zVykd
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fdzdi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___90CSv
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent4"}
                      data-plasmic-override={overrides.tableContent4}
                      className={classNames(projectcss.all, sty.tableContent4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hiaqp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3Ao8W
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___1W9Su
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8Fe4Y
                          )}
                        >
                          {"New Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mlwHr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gcLyZ
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__weaIl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jyFr4
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__tyjS)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oC98
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mnStd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qWaFm
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent5"}
                      data-plasmic-override={overrides.tableContent5}
                      className={classNames(projectcss.all, sty.tableContent5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__x1Exg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qRsuv
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__tKxol
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qNvAt
                          )}
                        >
                          {"New Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nw2Cp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qEv
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6Ooeh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wr3JF
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__csnWn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3XiPd
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hqv6R
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tbhd1
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent6"}
                      data-plasmic-override={overrides.tableContent6}
                      className={classNames(projectcss.all, sty.tableContent6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__aUtel
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ghyHw
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__c6Tes
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xAsJj
                          )}
                        >
                          {"New Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3Igtp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v75Hj
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__i7Svi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tjvlJ
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__diJfn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4NmqY
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__zga4X
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h84Uq
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"tableContent7"}
                      data-plasmic-override={overrides.tableContent7}
                      className={classNames(projectcss.all, sty.tableContent7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__tZj3C
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vmV5A
                          )}
                        >
                          {"10, Jan 2022"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__kZamL
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ilLhl
                          )}
                        >
                          {"New Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cqQz3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__v7OSf
                          )}
                        >
                          {"Tabungan Hari Tua"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ifOl1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__j2B3C
                          )}
                        >
                          {"Warior Staking"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mzWhv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___73Kh2
                          )}
                        >
                          {"USDT 100"}
                        </div>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__oVdD)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dvxJz
                          )}
                        >
                          {"Success"}
                        </div>
                      </div>
                    </div>
                  </p.Stack>
                </p.Stack>
              ) : null}
            </div>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "contentWrapper",
    "content",
    "head",
    "h1",
    "menubar",
    "portoflioWapper",
    "h3",
    "tabel",
    "tableHeader",
    "tableContent",
    "tableContent2",
    "tableContent3",
    "tableContent4",
    "tableContent5",
    "tableContent6",
    "tableContent7",
    "footer"
  ],
  navbar: ["navbar"],
  contentWrapper: [
    "contentWrapper",
    "content",
    "head",
    "h1",
    "menubar",
    "portoflioWapper",
    "h3",
    "tabel",
    "tableHeader",
    "tableContent",
    "tableContent2",
    "tableContent3",
    "tableContent4",
    "tableContent5",
    "tableContent6",
    "tableContent7"
  ],
  content: [
    "content",
    "head",
    "h1",
    "menubar",
    "portoflioWapper",
    "h3",
    "tabel",
    "tableHeader",
    "tableContent",
    "tableContent2",
    "tableContent3",
    "tableContent4",
    "tableContent5",
    "tableContent6",
    "tableContent7"
  ],
  head: ["head", "h1", "menubar"],
  h1: ["h1"],
  menubar: ["menubar"],
  portoflioWapper: [
    "portoflioWapper",
    "h3",
    "tabel",
    "tableHeader",
    "tableContent",
    "tableContent2",
    "tableContent3",
    "tableContent4",
    "tableContent5",
    "tableContent6",
    "tableContent7"
  ],
  h3: ["h3"],
  tabel: [
    "tabel",
    "tableHeader",
    "tableContent",
    "tableContent2",
    "tableContent3",
    "tableContent4",
    "tableContent5",
    "tableContent6",
    "tableContent7"
  ],
  tableHeader: ["tableHeader"],
  tableContent: ["tableContent"],
  tableContent2: ["tableContent2"],
  tableContent3: ["tableContent3"],
  tableContent4: ["tableContent4"],
  tableContent5: ["tableContent5"],
  tableContent6: ["tableContent6"],
  tableContent7: ["tableContent7"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  contentWrapper: "section";
  content: "div";
  head: "div";
  h1: "h1";
  menubar: typeof Menubar;
  portoflioWapper: "div";
  h3: "h3";
  tabel: "div";
  tableHeader: "div";
  tableContent: "div";
  tableContent2: "div";
  tableContent3: "div";
  tableContent4: "div";
  tableContent5: "div";
  tableContent6: "div";
  tableContent7: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicActivity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicActivity__VariantsArgs;
    args?: PlasmicActivity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicActivity__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicActivity__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicActivity__ArgProps,
          internalVariantPropNames: PlasmicActivity__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicActivity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicActivity";
  } else {
    func.displayName = `PlasmicActivity.${nodeName}`;
  }
  return func;
}

export const PlasmicActivity = Object.assign(
  // Top-level PlasmicActivity renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    contentWrapper: makeNodeComponent("contentWrapper"),
    content: makeNodeComponent("content"),
    head: makeNodeComponent("head"),
    h1: makeNodeComponent("h1"),
    menubar: makeNodeComponent("menubar"),
    portoflioWapper: makeNodeComponent("portoflioWapper"),
    h3: makeNodeComponent("h3"),
    tabel: makeNodeComponent("tabel"),
    tableHeader: makeNodeComponent("tableHeader"),
    tableContent: makeNodeComponent("tableContent"),
    tableContent2: makeNodeComponent("tableContent2"),
    tableContent3: makeNodeComponent("tableContent3"),
    tableContent4: makeNodeComponent("tableContent4"),
    tableContent5: makeNodeComponent("tableContent5"),
    tableContent6: makeNodeComponent("tableContent6"),
    tableContent7: makeNodeComponent("tableContent7"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicActivity
    internalVariantProps: PlasmicActivity__VariantProps,
    internalArgProps: PlasmicActivity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicActivity;
/* prettier-ignore-end */
