// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6jdiTgRhkYQJ2zXFv6Yaw9
// Component: bkX_qKyhqs
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MnItem from "../../MnItem"; // plasmic-import: OUU_m6iRfO/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_joss_staking.module.css"; // plasmic-import: 6jdiTgRhkYQJ2zXFv6Yaw9/projectcss
import sty from "./PlasmicMenubar.module.css"; // plasmic-import: bkX_qKyhqs/css

export type PlasmicMenubar__VariantMembers = {};

export type PlasmicMenubar__VariantsArgs = {};
type VariantPropType = keyof PlasmicMenubar__VariantsArgs;
export const PlasmicMenubar__VariantProps = new Array<VariantPropType>();

export type PlasmicMenubar__ArgsType = {
  dashboard?: React.ReactNode;
  portfolio?: React.ReactNode;
  activity?: React.ReactNode;
};

type ArgPropType = keyof PlasmicMenubar__ArgsType;
export const PlasmicMenubar__ArgProps = new Array<ArgPropType>(
  "dashboard",
  "portfolio",
  "activity"
);

export type PlasmicMenubar__OverridesType = {
  root?: p.Flex<"div">;
  menubar?: p.Flex<"div">;
};

export interface DefaultMenubarProps {
  dashboard?: React.ReactNode;
  portfolio?: React.ReactNode;
  activity?: React.ReactNode;
  className?: string;
}

function PlasmicMenubar__RenderFunc(props: {
  variants: PlasmicMenubar__VariantsArgs;
  args: PlasmicMenubar__ArgsType;
  overrides: PlasmicMenubar__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"menubar"}
        data-plasmic-override={overrides.menubar}
        hasGap={true}
        className={classNames(projectcss.all, sty.menubar)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__uv1SD
              )}
              component={Link}
              href={`/`}
              platform={"nextjs"}
            >
              <MnItem
                className={classNames("__wab_instance", sty.mnItem__kzmFw)}
                isActive={true}
              >
                {"Dashboard"}
              </MnItem>
            </p.PlasmicLink>
          ),

          value: args.dashboard
        })}

        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__eBrGm
              )}
              component={Link}
              href={`/portfolio`}
              platform={"nextjs"}
            >
              <MnItem
                className={classNames("__wab_instance", sty.mnItem__gwUwl)}
              >
                {"Portfolio"}
              </MnItem>
            </p.PlasmicLink>
          ),

          value: args.portfolio
        })}

        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicLink
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__s9Bno
              )}
              component={Link}
              href={`/activity`}
              platform={"nextjs"}
            >
              <MnItem
                className={classNames("__wab_instance", sty.mnItem__u02Wq)}
              >
                {"Activity"}
              </MnItem>
            </p.PlasmicLink>
          ),

          value: args.activity
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "menubar"],
  menubar: ["menubar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  menubar: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenubar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenubar__VariantsArgs;
    args?: PlasmicMenubar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenubar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenubar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMenubar__ArgProps,
          internalVariantPropNames: PlasmicMenubar__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMenubar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenubar";
  } else {
    func.displayName = `PlasmicMenubar.${nodeName}`;
  }
  return func;
}

export const PlasmicMenubar = Object.assign(
  // Top-level PlasmicMenubar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menubar: makeNodeComponent("menubar"),

    // Metadata about props expected for PlasmicMenubar
    internalVariantProps: PlasmicMenubar__VariantProps,
    internalArgProps: PlasmicMenubar__ArgProps
  }
);

export default PlasmicMenubar;
/* prettier-ignore-end */
