// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6jdiTgRhkYQJ2zXFv6Yaw9
// Component: FESK9JnTIoiE
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: KhBkDGlzke/component
import Menubar from "../../Menubar"; // plasmic-import: bkX_qKyhqs/component
import MnItem from "../../MnItem"; // plasmic-import: OUU_m6iRfO/component
import Agregate from "../../Agregate"; // plasmic-import: AHVlMwmS1K/component
import ProductCard from "../../ProductCard"; // plasmic-import: 7imsr4jILL/component
import Footer from "../../Footer"; // plasmic-import: oeSuO0WaA0/component

import { useScreenVariants as useScreenVariantsyddWx7I3Gw2DK } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: YddWx7I3Gw2dK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_joss_staking.module.css"; // plasmic-import: 6jdiTgRhkYQJ2zXFv6Yaw9/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: FESK9JnTIoiE/css

import UsdtSvgrepoComsvgIcon from "./icons/PlasmicIcon__UsdtSvgrepoComsvg"; // plasmic-import: Tj7RwiE503/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  contentWrapper?: p.Flex<"section">;
  content?: p.Flex<"div">;
  head?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  menubar?: p.Flex<typeof Menubar>;
  dataAgregate?: p.Flex<"div">;
  columns?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  h3?: p.Flex<"h3">;
  productList?: p.Flex<"div">;
  productImage4?: p.Flex<typeof p.PlasmicImg>;
  productImage5?: p.Flex<typeof p.PlasmicImg>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsyddWx7I3Gw2DK()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <p.Stack
            as={"section"}
            data-plasmic-name={"contentWrapper"}
            data-plasmic-override={overrides.contentWrapper}
            hasGap={true}
            className={classNames(projectcss.all, sty.contentWrapper)}
          >
            <div
              data-plasmic-name={"content"}
              data-plasmic-override={overrides.content}
              className={classNames(projectcss.all, sty.content)}
            >
              <div
                data-plasmic-name={"head"}
                data-plasmic-override={overrides.head}
                className={classNames(projectcss.all, sty.head)}
              >
                <div className={classNames(projectcss.all, sty.column__qr3AE)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Joss Stake"}
                  </h1>
                </div>

                <div className={classNames(projectcss.all, sty.column___1Xd7)}>
                  <Menubar
                    data-plasmic-name={"menubar"}
                    data-plasmic-override={overrides.menubar}
                    className={classNames("__wab_instance", sty.menubar)}
                  />
                </div>
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"dataAgregate"}
                data-plasmic-override={overrides.dataAgregate}
                hasGap={true}
                className={classNames(projectcss.all, sty.dataAgregate)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__vyaIr)}
                  >
                    <Agregate
                      className={classNames(
                        "__wab_instance",
                        sty.agregate__f5ENi
                      )}
                      slot3={
                        true ? (
                          <UsdtSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uzBKd
                            )}
                            role={"img"}
                          />
                        ) : null
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__blEkI)}
                  >
                    <Agregate
                      className={classNames(
                        "__wab_instance",
                        sty.agregate__myUuE
                      )}
                      slot={"Total Reward"}
                      slot3={
                        true ? (
                          <UsdtSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xvxGk
                            )}
                            role={"img"}
                          />
                        ) : null
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__xFjSj)}
                  >
                    <Agregate
                      className={classNames(
                        "__wab_instance",
                        sty.agregate___1Yw8R
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qJeO4
                          )}
                        >
                          {"Total Portfolio"}
                        </div>
                      }
                      slot2={
                        true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vz0ON
                            )}
                          >
                            {""}
                          </div>
                        ) : null
                      }
                      slot3={
                        true ? (
                          <UsdtSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hLUsT
                            )}
                            role={"img"}
                          />
                        ) : null
                      }
                    >
                      {"1"}
                    </Agregate>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__kssJx)}
                  >
                    <Agregate
                      className={classNames(
                        "__wab_instance",
                        sty.agregate__kqbn
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xrVkC
                          )}
                        >
                          {"Wallet Balance"}
                        </div>
                      }
                      slot2={
                        true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__x4HnG
                            )}
                          >
                            {""}
                          </div>
                        ) : null
                      }
                    >
                      {"1.000"}
                    </Agregate>
                  </div>
                </p.Stack>
              </p.Stack>

              {true ? (
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {"Product"}
                  </h3>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"productList"}
                    data-plasmic-override={overrides.productList}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.productList)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__acWrs)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__unRwl
                        )}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__eb18F)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__i6Cl
                        )}
                        productImage={
                          <p.PlasmicImg
                            data-plasmic-name={"productImage4"}
                            data-plasmic-override={overrides.productImage4}
                            alt={""}
                            className={classNames(sty.productImage4)}
                            displayHeight={"90px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"90px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/joss_staking/images/epicpng.png",
                              fullWidth: 90,
                              fullHeight: 90,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        slot={"🤟 Medium Risk"}
                      >
                        {"Epic Staking"}
                      </ProductCard>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__o15Ja)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__vQy2Y
                        )}
                        productImage={
                          <p.PlasmicImg
                            data-plasmic-name={"productImage5"}
                            data-plasmic-override={overrides.productImage5}
                            alt={""}
                            className={classNames(sty.productImage5)}
                            displayHeight={"90px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"90px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/joss_staking/images/legendpng.png",
                              fullWidth: 90,
                              fullHeight: 90,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        slot={"🔥 High Risk"}
                      >
                        {"Legend Staking"}
                      </ProductCard>
                    </div>
                  </p.Stack>
                </p.Stack>
              ) : null}
            </div>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "contentWrapper",
    "content",
    "head",
    "h1",
    "menubar",
    "dataAgregate",
    "columns",
    "freeBox",
    "h3",
    "productList",
    "productImage4",
    "productImage5",
    "footer"
  ],
  navbar: ["navbar"],
  contentWrapper: [
    "contentWrapper",
    "content",
    "head",
    "h1",
    "menubar",
    "dataAgregate",
    "columns",
    "freeBox",
    "h3",
    "productList",
    "productImage4",
    "productImage5"
  ],
  content: [
    "content",
    "head",
    "h1",
    "menubar",
    "dataAgregate",
    "columns",
    "freeBox",
    "h3",
    "productList",
    "productImage4",
    "productImage5"
  ],
  head: ["head", "h1", "menubar"],
  h1: ["h1"],
  menubar: ["menubar"],
  dataAgregate: ["dataAgregate", "columns"],
  columns: ["columns"],
  freeBox: ["freeBox", "h3", "productList", "productImage4", "productImage5"],
  h3: ["h3"],
  productList: ["productList", "productImage4", "productImage5"],
  productImage4: ["productImage4"],
  productImage5: ["productImage5"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  contentWrapper: "section";
  content: "div";
  head: "div";
  h1: "h1";
  menubar: typeof Menubar;
  dataAgregate: "div";
  columns: "div";
  freeBox: "div";
  h3: "h3";
  productList: "div";
  productImage4: typeof p.PlasmicImg;
  productImage5: typeof p.PlasmicImg;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    contentWrapper: makeNodeComponent("contentWrapper"),
    content: makeNodeComponent("content"),
    head: makeNodeComponent("head"),
    h1: makeNodeComponent("h1"),
    menubar: makeNodeComponent("menubar"),
    dataAgregate: makeNodeComponent("dataAgregate"),
    columns: makeNodeComponent("columns"),
    freeBox: makeNodeComponent("freeBox"),
    h3: makeNodeComponent("h3"),
    productList: makeNodeComponent("productList"),
    productImage4: makeNodeComponent("productImage4"),
    productImage5: makeNodeComponent("productImage5"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
